arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - meca_axis_1_joint
    - meca_axis_2_joint
    - meca_axis_3_joint
    - meca_axis_4_joint
    - meca_axis_5_joint
    - meca_axis_6_joint

