controller_list:
  - name: fake_meca500_arm_controller
    type: $(arg execution_type)
    joints:
      - meca_axis_1_joint
      - meca_axis_2_joint
      - meca_axis_3_joint
      - meca_axis_4_joint
      - meca_axis_5_joint
      - meca_axis_6_joint
initial:  # Define initial robot poses.
#  - group: meca500_arm
#    pose: home

  []